spring.application.name=habit-tracker-api
server.port=8080

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:rootpassword@localhost:27017/habitdb?authSource=admin}
app.seed.enabled=${APP_SEED_ENABLED:true}
